name: Uptime Check

on:
  schedule:
    # Run every 5 minutes
    - cron: '0 * * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  check_uptime:
    runs-on: ubuntu-latest
    steps:
      - name: Check Website Uptime
        run: |
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}" https://jonathanthom.com)
          if [ "$STATUS_CODE" != "200" ]; then
            echo "Uptime check failed: Website returned HTTP $STATUS_CODE"
            exit 1
          else
            echo "Uptime check passed: Website returned HTTP $STATUS_CODE"
          fi
